import { Roboto } from 'next/font/google'

const roboto = Roboto({
  weight: ['300', '400', '700'],
  subsets: ['latin']
 })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en-us">
      <body className={roboto.className}
         suppressHydrationWarning={true} 
      >
        {children}
      </body>
    </html>
  )
}
